export const UI_SNACKBAR_OPEN = 'UI_SNACKBAR_OPEN';
export const UI_SNACKBAR_CLOSE = 'UI_SNACKBAR_CLOSE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOAD_USER_PENDING = 'LOAD_USER_PENDING';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const FETCH_QUIZZES_PENDING = 'FETCH_QUIZZES_PENDING';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZZES_FAILURE = 'FETCH_QUIZZES_FAILURE';

export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';

export const FETCH_QUIZ_PENDING = 'FETCH_QUIZ_PENDING';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAILURE = 'FETCH_QUIZ_FAILURE';

export const DELETE_QUIZ_PENDING = 'DELETE_QUIZ_PENDING';
export const DELETE_QUIZ_SUCCESS = 'DELETE_QUIZ_SUCCESS';
export const DELETE_QUIZ_FAILURE = 'DELETE_QUIZ_FAILURE';

export const EDIT_QUIZ_PENDING = 'EDIT_QUIZ_PENDING';
export const EDIT_QUIZ_SUCCESS = 'EDIT_QUIZ_SUCCESS';
export const EDIT_QUIZ_FAILURE = 'EDIT_QUIZ_FAILURE';
